export const  BACKGROUND_COLOR_PRIMARY = '#FF5C00';
export const  BACKGROUND_COLOR_SECONDARY = '#FFFFFF';
export const  INPUT_TITLE_COLOR = '#646464';
export const  INPUT_PLACEHOLDER_COLOR = '#8398AE';
export const  INPUT_VALIDATION_TEXT_COLOR = '#EE0000';
export const  BUTTON_BACKGROUND_COLOR = '#EDEDED';
export const  BUTTON_TEXT_COLOR = '#646464';
export const  TITLE_SCREEN_TEXT_COLOR = '#FFFFFF';





